[versions]
netty = "4.2.9.Final"

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }

[libraries]
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }
netty-transport-epoll = { group = "io.netty", name = "netty-transport-native-epoll", version.ref = "netty" }

velocity = "com.velocitypowered:velocity-api:3.4.0-SNAPSHOT"